version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

    steps:
      - checkout

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libpng-dev

      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install gd
      - run: sudo docker-php-ext-install pdo
      - run: sudo docker-php-ext-install pdo_sqlite && docker-php-ext-enable pdo_sqlite

      - run: sudo composer self-update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer update && composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: php artisan migrate --env=testing --force

      - run: npm run production
      - run: ./vendor/bin/phpunit

      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
