<?php

namespace Tests\Feature\Http\Controllers;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\BasketController
 */
class BasketControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function add_product_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user)->post(route('basket.add-product'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function clear_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user)->get(route('basket.empty'));

        $response->assertOk();
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user)->get(route('basket'));

        $response->assertOk();
        $response->assertViewIs('basket.index');
        $response->assertViewHas('basket');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function remove_product_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user)->post(route('basket.delete-line'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
