<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ProductController
 */
class ProductControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('products'));

        $response->assertOk();
        $response->assertViewIs('products.products');
        $response->assertViewHas('categories');
        $response->assertViewHas('sub_category_list');
        $response->assertViewHas('products');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('products.search'));

        $response->assertOk();
        $response->assertViewIs('products.products');
        $response->assertViewHas('products');
        $response->assertViewHas('categories');
        $response->assertViewHas('sub_category_list');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $product = factory(\App\Models\Product::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('products.show', [$product]));

        $response->assertOk();
        $response->assertViewIs('products.show');
        $response->assertViewHas('categories');
        $response->assertViewHas('product');

        // TODO: perform additional assertions
    }

    // test cases...
}
