<?php

namespace Tests\Feature\Http\Controllers\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Auth\AdminController
 */
class AdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('cms.login.submit'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(intended(route('cms.index')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function logout_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user, 'admin')->post(route('cms.logout'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('cms.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_login_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('cms.login'));

        $response->assertOk();
        $response->assertViewIs('authentication.login');

        // TODO: perform additional assertions
    }

    // test cases...
}
