<?php

namespace Tests\Feature\Http\Controllers\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Auth\AdminForgotPasswordController
 */
class AdminForgotPasswordControllerTest extends TestCase
{
    /**
     * @test
     */
    public function send_reset_link_email_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('cms.password-email'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('authentication.passwords.email');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_link_request_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('cms.forgot-password'));

        $response->assertOk();
        $response->assertViewIs('authentication.passwords.email');

        // TODO: perform additional assertions
    }

    // test cases...
}
