<?php

namespace Tests\Feature\Http\Controllers\Cms;

use App\Models\Contact;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Cms\ContactController
 */
class ContactControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contact = factory(Contact::class)->create();
        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->delete(route('cms.contacts.delete', [$contact]));

        $response->assertOk();
        $this->assertDeleted($cms);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->get(route('cms.contacts'));

        $response->assertOk();
        $response->assertViewIs('contacts.index');
        $response->assertViewHas('contacts');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->post(route('cms.contacts.store'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contact = factory(Contact::class)->create();
        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')
            ->patch(route('cms.contacts.update', [$contact]), [// TODO: send request data
            ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
