<?php

namespace Tests\Feature\Http\Controllers\Cms;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Cms\DiscountsController
 */
class DiscountsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->delete(route('cms.discounts.customer-destroy', ['id' => $id]));

        $response->assertOk();
        $this->assertDeleted($cms);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function global_store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')
            ->post(route('cms.discounts.global-store'), [// TODO: send request data
            ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->get(route('cms.discounts'));

        $response->assertOk();
        $response->assertViewIs('discounts.index');
        $response->assertViewHas('global_discount');
        $response->assertViewHas('customer_discounts');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')
            ->post(route('cms.discounts.customer-store'), [// TODO: send request data
            ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
