<?php

namespace Tests\Feature\Http\Controllers\Cms;

use App\Models\HomeLink;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Cms\HomeLinksController
 */
class HomeLinksControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $home_link = factory(HomeLink::class)->create();
        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->delete(route('cms.home-links.delete', ['id' => $home_link->id]));

        $response->assertOk();
        $this->assertDeleted($cms);
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->get(route('cms.home-links'));

        $response->assertOk();
        $response->assertViewIs('home-links.index');
        $response->assertViewHas('category_top_level');
        $response->assertViewHas('categories');
        $response->assertViewHas('adverts');
        $response->assertViewHas('banners');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->post(route('cms.home-links.store'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_positions_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->patch(route('cms.home-links.update'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
