<?php

namespace Tests\Feature\Http\Controllers\Cms;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Cms\ProductDataController
 */
class ProductDataControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->get(route('cms.product-data'));

        $response->assertOk();
        $response->assertViewIs('product-data-settings.index');
        $response->assertViewHas('settings');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->patch(route('cms.product-data.update'), [// TODO: send request data
        ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
