<?php

namespace Tests\Feature\Http\Controllers\Cms;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Cms\SiteSettingsController
 */
class SiteSettingsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')->get(route('cms.site-settings'));

        $response->assertOk();
        $response->assertViewIs('site-settings.index');
        $response->assertViewHas('data');
        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(User::class)->create();

        $response = $this->actingAs($user, 'admin')
            ->patch(route('cms.site-settings.update'), [// TODO: send request data
            ]);

        $response->assertOk();
        // TODO: perform additional assertions
    }
    // test cases...
}
